[package]
name = "lighttpd_rust_amalgamated"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
c2rust-bitfields = "0.17.0"
libc = "0.2.140"
